CREATE TABLE tbl_member(
    m_seq	NUMBER		PRIMARY KEY,
    m_email	VARCHAR2(125)	NOT NULL	UNIQUE,	
    m_tel	VARCHAR2(13)	NOT NULL	UNIQUE,
    m_id	VARCHAR2(125)	NOT NULL	UNIQUE,
    m_pw	VARCHAR2(125)	NOT NULL,
    m_role	VARCHAR2(20)
);

CREATE SEQUENCE seq_test
START WITH 1
INCREMENT BY 1;

